---
version: '3.5'

services:
  app:
    build: src
    container_name: go-app
    ports:
      - "8080:8080"
    env_file:
      - vars.env
    entrypoint: "dockerize -wait tcp://postgres-db:5432 -timeout 60s"
    command: ["./main"]
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    container_name: postgres-db
    hostname: postgres-db
    env_file:
      - vars.env
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local